FROM ubuntu:latest

RUN apt update -y && \
  apt install -y \
    curl \
    wget \
    net-tools \
    procps \
    iproute2 \
    nmap \
    telnet \
    iputils-ping \
    vim \
    openjdk-8-jre-headless \
    openssh-client \
    traceroute